= Installation Methods
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-08-24
:page-revdate: {revdate}

[IMPORTANT] 
====
If your node has NetworkManager installed and enabled, xref:known_issues.adoc#_networkmanager[ensure that it is configured to ignore CNI-managed interfaces].
====

[IMPORTANT]
====
You can use any RKE2 Prime version listed on the Prime Artifacts URL for the assets mentioned in these steps. To learn more about the Prime Artifacts URL, see our https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime-only documentation]. Authentication is required. Use your https://scc.suse.com/home[SUSE Customer Center (SCC)] credentials to log in.
====

RKE2 can be installed to a system in a number of ways, two of which are the preferred and supported methods. Those methods are tarball and RPM. The install script referenced in the Quick Start is a wrapper around these two methods.

This document explains these installation methods in greater detail.

[#_tarball]
== Tarball

To install RKE2 via install you first need to get the install script. This can be done in a number of ways.

This gets the script and immediately starts the installation process.

[,sh]
----
# curl -sfL https://get.rke2.io | sudo sh -
curl -sfL https://get.rke2.io | sh -
----

Alternatively, you can download the install script and make it executable.

[,sh]
----
curl -sfL https://get.rke2.io --output install.sh
chmod +x install.sh
----

[#_installation_1]
=== Installation

Run the installer, where `INSTALL_RKE2_ARTIFACT_URL` is the Prime Artifacts URL and `INSTALL_RKE2_CHANNEL` is a release channel you can subscribe to and defaults to stable. In this example, `INSTALL_RKE2_CHANNEL="latest"` gives you the latest version of RKE2.

[,bash]
----
sudo INSTALL_RKE2_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/rke2 INSTALL_RKE2_CHANNEL="latest" ./install.sh
----

If you want to specify a version, set the `INSTALL_RKE2_VERSION` environment variable.

[,bash]
----
sudo INSTALL_RKE2_ARTIFACT_URL=<PRIME-ARTIFACTS-URL>/rke2 INSTALL_RKE2_VERSION="<VERSION>" ./install.sh
----

This will install the `rke2-server` service and the `rke2` binary onto your machine. Due to its nature, it will fail unless it runs as the root user or through `sudo`.

When the install script is executed, it makes a determination of what type of system it is. If it's an OS that uses RPMs (such as CentOS or RHEL), it will perform an RPM based installation, otherwise the script defaults to tarball. RPM based installation is covered below.

Next, the installation script downloads the tarball, verifies it by comparing SHA256 hashes, and lastly, extracts the contents to `/usr/local`. An operator is free to move the files after installation if desired. This operation simply extracts the tarball and no other system modifications are made.

Tarball structure / contents:

* bin - contains the RKE2 executable as well as the `rke2-killall.sh` and `rke2-uninstall.sh` scripts.
* lib - contains server and agent systemd unit files.
* share - contains the RKE2 license as well as a sysctl configuration file used for when RKE2 is ran in CIS mode.

To configure the system any further, you'll want to reference either the xref:reference/server_config.adoc[server] or xref:reference/linux_agent_config.adoc[agent] documentation.

[#_rpm]
== RPM

To start the RPM install process, you need to get the installation script which is covered above. The script will check your system for `zypper` and if it exists, it determines that the system is SUSE based and starts the RPM install process, writing the repository to `/etc/zypp/repos.d` and going through `transactional-update` when the root filesystem is immutable.

On Red Hat based systems, the script will check your system for `rpm`, `yum`, or `dnf` and if any of those exist, it determines that the system is Redhat based and starts the RPM install process from `/etc/yum.repos.d`.

Files are installed with the prefix of `/usr` rather than `/usr/local`.

[#_repositories]
=== Repositories

RKE2 provides signed RPMs in the `rpm.rancher.io` and `rpm-testing.rancher.io` repositories, which you can install manually or via the https://get.rke2.io/ script. The script automatically uses RPMs on SLES 16 and CentOS 8, 9, and 10. However, SLE Micro and MicroOS default to a tarball installation; to use RPMs on those systems, you must run the script with the `INSTALL_RKE2_METHOD=rpm` flag.

The RPMs provide `systemd` units for managing `rke2`, but will need to be configured via configuration file before starting the services for the first time.

Select your distribution below for the matching repository definition and install commands.

[tabs,sync-group-id=rpm-distro]
=====
SLES 16::
+
--
SUSE Linux Enterprise Server 16 uses the `slemicro` repository:

[,bash]
----
export RKE2_MINOR=36
cat << EOF > /etc/zypp/repos.d/rancher-rke2-1-${RKE2_MINOR}-latest.repo
[rancher-rke2-common-latest]
name=Rancher RKE2 Common Latest
baseurl=https://rpm.rancher.io/rke2/latest/common/slemicro/noarch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key

[rancher-rke2-1-${RKE2_MINOR}-latest]
name=Rancher RKE2 1.${RKE2_MINOR} Latest
baseurl=https://rpm.rancher.io/rke2/latest/1.${RKE2_MINOR}/slemicro/x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

After the repository is configured, install the package:

[,sh]
----
zypper --gpg-auto-import-keys install -y rke2-server
----

Replace `rke2-server` with `rke2-agent` on agent nodes.
--

SLE Micro::
+
--
SLE Micro uses the `slemicro` repository:

[,bash]
----
export RKE2_MINOR=36
cat << EOF > /etc/zypp/repos.d/rancher-rke2-1-${RKE2_MINOR}-latest.repo
[rancher-rke2-common-latest]
name=Rancher RKE2 Common Latest
baseurl=https://rpm.rancher.io/rke2/latest/common/slemicro/noarch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key

[rancher-rke2-1-${RKE2_MINOR}-latest]
name=Rancher RKE2 1.${RKE2_MINOR} Latest
baseurl=https://rpm.rancher.io/rke2/latest/1.${RKE2_MINOR}/slemicro/x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

SLE Micro is an immutable distribution, so the root filesystem is read-only and the install must go through `transactional-update`, requiring a reboot to take effect:

[,sh]
----
transactional-update --no-selfupdate -d run zypper --gpg-auto-import-keys install -y rke2-server
reboot
----

Replace `rke2-server` with `rke2-agent` on agent nodes.
--

MicroOS::
+
--
MicroOS uses the `microos` repository:

[,bash]
----
export RKE2_MINOR=36
cat << EOF > /etc/zypp/repos.d/rancher-rke2-1-${RKE2_MINOR}-latest.repo
[rancher-rke2-common-latest]
name=Rancher RKE2 Common Latest
baseurl=https://rpm.rancher.io/rke2/latest/common/microos/noarch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key

[rancher-rke2-1-${RKE2_MINOR}-latest]
name=Rancher RKE2 1.${RKE2_MINOR} Latest
baseurl=https://rpm.rancher.io/rke2/latest/1.${RKE2_MINOR}/microos/x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

MicroOS is an immutable distribution, so the root filesystem is read-only and the install must go through `transactional-update`, requiring a reboot to take effect:

[,sh]
----
transactional-update --no-selfupdate -d run zypper --gpg-auto-import-keys install -y rke2-server
reboot
----

Replace `rke2-server` with `rke2-agent` on agent nodes.
--

Enterprise Linux 8/9/10::
+
--
In order to use the RPM repository, on a CentOS or RHEL system, run the following bash snippet:

[,bash]
----
export RKE2_MINOR=36
export LINUX_MAJOR=8 # or 9 or 10 etc
cat << EOF > /etc/yum.repos.d/rancher-rke2-1-${RKE2_MINOR}-latest.repo
[rancher-rke2-common-latest]
name=Rancher RKE2 Common Latest
baseurl=https://rpm.rancher.io/rke2/latest/common/centos/${LINUX_MAJOR}/noarch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key

[rancher-rke2-1-${RKE2_MINOR}-latest]
name=Rancher RKE2 1.${RKE2_MINOR} Latest
baseurl=https://rpm.rancher.io/rke2/latest/1.${RKE2_MINOR}/centos/${LINUX_MAJOR}/x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
EOF
----

After the repository is configured, you can run either of the following commands:

[,sh]
----
yum -y install rke2-server
----

or

[,sh]
----
yum -y install rke2-agent
----
--
=====

The RPM will install a corresponding `rke2-server.service` or `rke2-agent.service` systemd unit that can be invoked like: `systemctl start rke2-server`. Make sure that you configure `rke2` before you start it, by following the `Configuration File` instructions below.

[#_manual]
== Manual

The RKE2 binary is statically compiled and linked which allows for the RKE2 binary to be portable across Linux distributions without the concern for dependency issues. The simplest installation is to download the binary, make sure it's executable, and copy it into the `+$<PATH>+`, generally `/usr/local/bin`. After first execution, RKE2 will create all necessary directories and files. To configure the system any further, you'll want to reference the xref:install/configuration.adoc[config file] documentation.
