= Gerenciando Componentes Empacotados
:page-languages: [en, zh]
:revdate: 2025-08-06
:page-revdate: {revdate}

== Manifestos de Implantação Automática (AddOns)

Nos nós do servidor, qualquer arquivo encontrado em `/var/lib/rancher/rke2/server/manifests` será automaticamente implantado no Kubernetes de maneira semelhante a `kubectl apply`, tanto na inicialização quanto quando o arquivo for alterado no disco. Excluir arquivos deste diretório não excluirá os recursos correspondentes do cluster.

Os manifestos são rastreados como recursos personalizados `AddOn` no namespace `kube-system`. Quaisquer erros ou avisos encontrados ao aplicar o arquivo de manifesto podem ser vistos usando `kubectl describe` no `AddOn` correspondente, ou usando `kubectl get event -n kube-system` para visualizar todos os eventos para esse namespace, incluindo aqueles do controlador de implantação.

=== Componentes Empacotados

O RKE2 vem com vários componentes empacotados que são implantados como AddOns através do diretório, por exemplo `rke2-coredns`, `rke2-metrics-server`, `rke2-ingress-nginx` e assim por diante.

Os manifestos para componentes empacotados são gerenciados pelo RKE2 e não devem ser alterados. Os arquivos são reescritos no disco sempre que o RKE2 é iniciado, a fim de garantir sua integridade.

=== AddOns do Usuário

Você pode colocar arquivos adicionais no diretório de manifestos para implantação como um `AddOn`. Cada arquivo pode conter múltiplos recursos do Kubernetes, delimitados pelo separador de documentos YAML `---`. Para mais informações sobre como organizar recursos em manifestos, consulte a seção https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/[Gerenciando Recursos] da documentação do Kubernetes.

==== Requisitos de Nomeação de Arquivos

O nome de arquivo `AddOn` para cada arquivo no diretório de manifestos é derivado do nome base do arquivo. Certifique-se de que todos os arquivos dentro do diretório de manifestos (ou dentro de quaisquer subdiretórios) tenham nomes que sejam únicos e que atendam às https://kubernetes.io/docs/concepts/overview/working-with-objects/names/[restrições de nomenclatura de objetos] do Kubernetes. Deve-se também ter cuidado para não entrar em conflito com nomes utilizados pelos componentes padrão empacotados do RKE2, mesmo que esses componentes estejam desativados.

[CAUTION]
====
Se você tiver vários nós de servidor e colocar manifestos adicionais de AddOn em mais de um servidor, é sua responsabilidade garantir que os arquivos permaneçam sincronizados entre esses nós. O RKE2 não sincroniza o conteúdo do AddOn entre os nós e não pode garantir o comportamento correto se servidores diferentes tentarem implantar manifestos conflitantes.
====

== Desabilitando Manifestos

Existem duas maneiras de desabilitar a implantação de conteúdo específico do diretório de manifestos.

=== Usando a flag `--disable`

Os AddOns para os componentes empacotados listados acima, além dos AddOns para quaisquer manifestos adicionais colocados no diretório `manifests`, podem ser desabilitados com a flag `--disable`. AddOns desabilitados são desinstalados ativamente do cluster, e os arquivos de origem são excluídos do diretório `manifests`.

Por exemplo, para impedir que o metrics-server seja instalado em um novo cluster, ou para desinstalá-lo e remover o manifesto de um cluster existente, você pode iniciar o RKE2 com `--disable=rke2-metrics-server`. Vários itens podem ser desabilitados separando seus nomes com vírgulas, ou repetindo a flag.

=== Usando arquivos .skip

Para qualquer arquivo sob `/var/lib/rancher/rke2/server/manifests`, você pode criar um arquivo `.skip` que fará com que o RKE2 ignore o manifesto correspondente. O conteúdo do arquivo `.skip` não importa, apenas sua existência é verificada. Observe que criar um arquivo `.skip` após um AddOn já ter sido criado não removerá ou modificará de outra forma, nem os recursos que ele criou; o arquivo é simplesmente tratado como se não existisse.

== AddOns do Helm

Para informações sobre como gerenciar os charts do Helm por meio da implantação automática de manifestos, consulte a seção sobre xref:add-ons/helm.adoc[Helm].
