= GPU Operators
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-08-24
:page-revdate: {revdate}

This guide shows how to deploy, manage and verify GPU resources in RKE2 clusters.
It covers installation, host requirements, and validation for both NVIDIA and AMD GPU operators.

[#_deploy_nvidia_operator]
== Deploy NVIDIA operator

The https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html[NVIDIA operator] allows administrators of Kubernetes clusters to manage GPUs just like CPUs. It includes everything needed for pods to operate GPUs.

[#_host_os_requirements]
=== Host OS requirements

To expose the GPU to the pod correctly, the NVIDIA kernel drivers and the `libnvidia-ml` library must be correctly installed in the host OS (Operating System). The NVIDIA Operator can automatically install drivers and libraries on some operating systems. Refer to the NVIDIA documentation for information on https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html#supported-operating-systems-and-kubernetes-platforms[supported operating system releases].

Starting with GPU Operator v26.3.x, the operator can also manage driver and library installation on any operating system, provided the OS vendor or administrator supplies a compatible driver container image.

Installation of the NVIDIA components on your host OS is out of the scope of this document; reference the NVIDIA documentation for instructions.

.Checks for pre-installed NVIDIA drivers/libraries
[%collapsible]
====
The following three commands should return a correct output if the kernel driver was correctly installed:

* `lsmod | grep nvidia` returns a list of nvidia kernel modules. For example:
+
[,sh]
----
nvidia_uvm           2129920  0
nvidia_drm            131072  0
nvidia_modeset       1572864  1 nvidia_drm
video                  77824  1 nvidia_modeset
nvidia               9965568  2 nvidia_uvm,nvidia_modeset
ecc                    45056  1 nvidia
----

* `cat /proc/driver/nvidia/version` returns the NVRM and GCC version of the driver. For example:
+
[,sh]
----
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  555.42.06  Release Build  (abuild@host)  Thu Jul 11 12:00:00 UTC 2024
GCC version:  gcc version 7.5.0 (SUSE Linux)
----

* `find /usr/ -iname libnvidia-ml.so` returns a path to the `libnvidia-ml.so` library. For example:
+
[,sh]
----
/usr/lib64/libnvidia-ml.so
----
+
This library is used by Kubernetes components to interact with the kernel driver.
====

[#_operator_installation]
=== Operator installation

Once the OS is ready and RKE2 is running, install the GPU Operator with the following yaml manifest.

[tabs,sync-group-id=GPUoperator]
=====
v25.3.x::
+
--

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  version: v25.3.4
  targetNamespace: gpu-operator
  createNamespace: true
  valuesContent: |-
    toolkit:
      env:
      - name: CONTAINERD_SOCKET
        value: /run/k3s/containerd/containerd.sock
      - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
        value: "false"
      - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS
        value: "true"
    devicePlugin:
      env:
      - name: DEVICE_LIST_STRATEGY
        value: volume-mounts
----

[NOTE]
====
The envvars `ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED`, `ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS` and `DEVICE_LIST_STRATEGY` are required to properly isolate GPU resources as explained in this nvidia https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit?tab=t.0[doc]
====

[CAUTION]
====
The NVIDIA operator restarts containerd with a hangup call which restarts RKE2
====

--

v25.10.x::
+
--

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  version: v25.10.1
  targetNamespace: gpu-operator
  createNamespace: true
  valuesContent: |-
    toolkit:
      env:
      - name: CONTAINERD_SOCKET
        value: /run/k3s/containerd/containerd.sock
----

[NOTE]
====
NVIDIA GPU Operator v25.10.x uses https://github.com/cncf-tags/container-device-interface/blob/main/SPEC.md[Container Device Interface (CDI) specification] and that simplifies operations: we don't need to pass extra envvars to comply with the security requirements and the workloads do not need to pass the `runtimeClassName: nvidia` anymore. It requires containerd 2.0.
====

[CAUTION]
====
The NVIDIA operator restarts containerd with a hangup call which restarts RKE2
====

--

v26.3.x::
+
--

There are two installation options available.

If drivers and libraries are pre-installed or you are using a https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html#supported-operating-systems-and-kubernetes-platforms[supported operating system by nvidia], please use the following manifest:

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  version: v26.3.2
  targetNamespace: gpu-operator
  createNamespace: true
  valuesContent: |-
    toolkit:
      env:
      - name: CONTAINERD_SOCKET
        value: /run/k3s/containerd/containerd.sock
----

If your operating system vendor supplies a compatible driver image, you can use the `driver` value field to point to it. For example, in SLES 16.0, you can use the following manifest:

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  version: v26.3.2
  targetNamespace: gpu-operator
  createNamespace: true
  valuesContent: |-
    toolkit:
      env:
      - name: CONTAINERD_SOCKET
        value: /run/k3s/containerd/containerd.sock
    driver:
      repository: registry.suse.com/third-party/nvidia
      usePrecompiled: true
      version: 595 # This depends on the nvidia driver that works with your GPU architecture
----

--

v26.3.x with NRI::
+
--

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/cdi.html#about-the-node-resource-interface-nri-plugin[Node Resource Interface (NRI) specification] is a pluggable extension mechanism built into container runtimes like containerd and CRI-O that allows custom plugins to intercept container lifecycle events on a node. It is considered the future integration mechanism for GPUs.

[WARNING]
====
NVIDIA considers NRI as experimental
====

If you want to try it out, please use the following manifest:

[,yaml]
----
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  version: v26.3.1
  targetNamespace: gpu-operator
  createNamespace: true
  valuesContent: |-
    cdi:
      nriPluginEnabled: true
----

[IMPORTANT]
.Version Gate
====
NRI requires containerd 2.1. Containerd 2.1 is available as of September 2025 releases: v1.31.13+rke2r1, v1.32.9+rke2r1, v1.33.5+rke2r1, v1.34.1+rke2r1
====

--
=====

After a few minutes, you can perform the following checks to verify that everything is working as expected:

. Assuming the drivers and `libnvidia-ml.so` library were previously installed, check if the operator detects them correctly:
+
[,sh]
----
kubectl get node $NODENAME -o jsonpath='{.metadata.labels}' |  grep "nvidia.com"
----
+
You should see labels specifying driver and GPU (e.g. `nvidia.com/gpu.machine` or `nvidia.com/cuda.driver.major`).

. Check if the GPU was added by `nvidia-device-plugin-daemonset` as an allocatable resource in the node:
+
[,sh]
----
kubectl get node $NODENAME -o jsonpath='{.status.allocatable}'
----
+
You should see `"nvidia.com/gpu":` followed by the number of GPUs in the node.

. Check that the container runtime binary exists (it gets installed by the `nvidia-container-toolkit-daemonset`):
+
[,sh]
----
ls /usr/local/nvidia/toolkit/nvidia-container-runtime
----

. (Only if not using NRI) Verify if containerd config was updated to include the NVIDIA container runtime:
+
[,sh]
----
grep nvidia /var/lib/rancher/rke2/agent/etc/containerd/config.toml
----

. Run a pod to verify that the GPU resource can successfully be scheduled on a pod and the pod can detect it
+
[,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: nbody-gpu-benchmark
  namespace: default
spec:
  restartPolicy: OnFailure
  # runtimeClassName: nvidia <== Only needed for v25.3.x
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody
    args: ["nbody", "-gpu", "-benchmark"]
    resources:
      limits:
        nvidia.com/gpu: 1
----

RKE2 will now use `PATH` to find alternative container runtimes, in addition to checking the default paths used by the container runtime packages. In order to use this feature, you must modify the RKE2 service's PATH environment variable to add the directories containing the container runtime binaries.

It's recommended that you modify one of this two environment files:

* `/etc/default/rke2-server` # or rke2-agent
* `/etc/sysconfig/rke2-server` # or rke2-agent

This example will add the `PATH` in `/etc/default/rke2-server`:

[CAUTION]
====
`PATH` changes should be done with care to avoid placing untrusted binaries in the path of services that run as root.
====

[,bash]
----
echo PATH=$PATH >> /etc/default/rke2-server
----


[#_deploy_amd_operator]
== Deploy AMD operator on SLES

The AMD GPU Operator allows administrators of Kubernetes clusters to manage AMD GPUs just like CPUs.

On SLES, the operator uses precompiled `amdgpu` driver images from the link:http://registry.suse.com[Trusted container images repository]
built against the codestream's GA kernel. KMM relocates the modules to the node's
running kernel using SUSE's stable kABI guarantee--no recompilation needed across
kernel updates within the same codestream. The resulting image is pushed to your
registry of choice.

[TIP]
.Driver images for SLES
====
The prebuild driver images for specific SLES versions are available from the following links:
* SLES 16: link:https://registry.suse.com/repositories/third-party-amd-amdgpu-driver-sles16[]
* SLES 15: link:https://registry.suse.com/repositories/third-party-amd-amdgpu-driver-sles15[]
====

[TIP]
.Official AMD documentation
====
Find the official documentation for precompiled drivers at the following links:
* link:https://instinct.docs.amd.com/projects/gpu-operator/en/latest/installation/kubernetes-helm.html[]
* link:https://instinct.docs.amd.com/projects/gpu-operator/en/latest/drivers/precompiled-driver.html[]
====

[#_deploy_amd_operator_prerequisites]
=== Prerequisites

* Verify that an AMD GPU PCI device is present.
+
[,sh]
----
lspci -nn | grep -i "amd\|ati\|display\|vga"
----

* Verify that the RKE2 cluster is up and running.
+
[,sh]
----
kubectl get nodes
----

* Install link:https://documentation.suse.com/cloudnative/rancher-manager/v2.14/en/installation-and-upgrade/other-installation-methods/http-proxy/install-rancher.html#_install_cert_manager[cert-manager].
It is required for webhook TLS certificates.

[#_deploy_amd_operator_installing]
=== Installing AMD GPU Operator

. Add the operator repository and update it.
+
[,sh]
----
helm repo add rocm https://rocm.github.io/gpu-operator
helm repo update
----

. Install the operator.
+
[,sh]
----
helm install amd-gpu-operator rocm/gpu-operator-charts \
  --namespace kube-amd-gpu \
  --create-namespace \
  --version v1.5.1 \
  --set crds.defaultCR.install=false
----

. Wait for the operator's controller-manager pod to become ready.
+
[,sh]
----
kubectl wait --for=condition=ready pod \
  -l control-plane=controller-manager \
  -n kube-amd-gpu --timeout=300s
----

. Verify that the operator pods are running successfully.
+
[,sh]
----
kubectl get pods -n kube-amd-gpu
----

[#_deploy_amd_operator_deviceconfig]
=== Create DeviceConfig
The `DeviceConfig` resource tells the operator how to build and load the driver.
On SLES, set `imageBuild.baseImageRegistry: "registry.suse.com"`.
This tells the operator to fetch the pre-built AMD GPU driver image for your SLES codestream's GA kernel.
The operator then relocates the modules into the node's running kernel path using SUSE's stable kABI guarantee. 
As a result, no recompilation is needed across kernel updates within the same codestream. 

[,sh]
----
NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')

kubectl apply -f - <<EOF
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: amdgpu-sles
  namespace: kube-amd-gpu
spec:
  driver:
    enable: true
    blacklist: true
    image: ${NODE_IP}:${REGISTRY_PORT}/amdgpu-driver
    version: "31.40"
    imageBuild:
      baseImageRegistry: "registry.suse.com"
      baseImageRegistryTLS:
        insecure: true
        insecureSkipTLSVerify: true
  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:latest
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest
    enableNodeLabeller: true
  metricsExporter:
    enable: true
    serviceType: "NodePort"
    nodePort: 32500
    image: docker.io/rocm/device-metrics-exporter:v1.5.1
  selector:
    feature.node.kubernetes.io/amd-gpu: "true"
EOF
----

[TIP]
====
Refer to link:https://instinct.docs.amd.com/projects/amdgpu-docs/en/latest/release/versions.html[AMD GPU Driver release history] for available driver versions.
====

[#_deploy_amd_operator_verify]
== Verify the installation

After a few minutes, perform the following checks:

. Check that the kernel module was loaded on the node.
+
[,sh]
----
lsmod | grep amdgpu
----

. Check that the GPU was added as an allocatable resource.
+
[,sh]
----
kubectl get nodes -o custom-columns="NAME:.metadata.name,GPU:.status.allocatable.amd\.com/gpu"
----
+
You should see `1` or more for multi-GPU nodes in the `GPU` column.

. Check that the node labeller applied GPU hardware labels.
+
[,sh]
----
kubectl get node -o jsonpath='{.items[0].metadata.labels.amd\.com/gpu\.driver-version}{"\n"}'
kubectl get node -o jsonpath='{.items[0].metadata.labels.amd\.com/gpu\.product-name}{"\n"}'
kubectl get node -o jsonpath='{.items[0].metadata.labels.kmm\.node\.kubernetes\.io/version-module\.kube-amd-gpu\.amdgpu-sles}{"\n"}'
----

. Run a pod to verify the GPU can be scheduled and detected.
+
[,sh]
----
kubectl apply -f - <<'EOF'
apiVersion: v1
kind: Pod
metadata:
  name: amd-smi
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: amd-smi
    image: docker.io/rocm/pytorch:latest
    command: ["/bin/bash"]
    args: ["-c", "amd-smi version && amd-smi monitor -ptum"]
    resources:
      limits:
        amd.com/gpu: 1
      requests:
        amd.com/gpu: 1
EOF

kubectl wait --for=condition=ready pod/amd-smi --timeout=300s
kubectl logs amd-smi
kubectl delete pod amd-smi
----

[#_deploy_amd_operator_troublshoot]
== Troubleshooting

For troubleshooting issues with the AMD GPU operator, perform the following checks:

. View the operator controller-manager logs.
+
[,sh]
----
kubectl logs -n kube-amd-gpu -l control-plane=controller-manager --tail=50
----

. View the KMM build job logs (active while the image is being built).
+
[,sh]
----
kubectl logs -n kube-amd-gpu -l kmm.node.kubernetes.io/job-type=build --tail=100
----

. View the KMM worker logs to monitor module loading.
+
[,sh]
----
kubectl logs -n kube-amd-gpu \
  -l kmm.node.kubernetes.io/job-type=device-config --all-containers --tail=50
----

. Check the details and status of the DeviceConfig and Module resources.
+
[,sh]
----
kubectl describe deviceconfig amdgpu-sles -n kube-amd-gpu
kubectl describe module amdgpu-sles -n kube-amd-gpu
----

. Inspect kernel messages related to the AMD GPU modules.
+
[,sh]
----
dmesg | grep -i "amdgpu\|amdkcl\|amdttm" | tail -30
----

For more details, refer to the link:https://instinct.docs.amd.com/projects/gpu-operator/en/latest/troubleshooting.html[AMD GPU Operator Troubleshooting documentation].

[#_deploy_amd_operator_uninstall]
== Cleanup

To uninstall the AMD GPU operator and its associated components, perform the following steps:

. Delete the custom `DeviceConfig` resource.
+
[,sh]
----
kubectl delete deviceconfig amdgpu-sles -n kube-amd-gpu
----

. Uninstall the AMD GPU operator and cert-manager Helm charts.
+
[,sh]
----
helm uninstall amd-gpu-operator -n kube-amd-gpu
helm uninstall cert-manager -n cert-manager
----

. Delete the `kube-amd-gpu` and `cert-manager` namespaces.
+
[,sh]
----
kubectl delete namespace kube-amd-gpu cert-manager
----