= RKE2のロールバック
:page-languages: [en, zh]
:revdate: 2025-12-04
:page-revdate: {revdate}

アップグレード後にRKE2のKubernetesバージョンをロールバックするには、RKE2バイナリのダウングレードとデータストアの復元を組み合わせて使用できます。ロールバックは、シングルノードのSQLite、外部データストア、または組み込みのetcdを含むすべてのタイプのクラスターで実行できます。以前のKubernetesマイナーバージョンにロールバックする場合、ロールバック先のKubernetesマイナーバージョンで取得したデータストアのスナップショットが必要です。

[CAUTION]
====
データベースを復元できない場合、以前のマイナーバージョンにロールバックすることはできません。
====

== 重要な考慮事項

* *バックアップ:*アップグレード前に、古いバージョンのRKE2を実行しているクラスターから有効なデータベースまたはetcdのスナップショットを取得していることを確認してください。バックアップがない場合、ロールバックは不可能です。
* *データ損失の可能性:*`rke2-killall.sh`スクリプトはRKE2プロセスを強制終了し、アプリケーションが適切にシャットダウンされていない場合、データ損失が発生する可能性があります。
* *バージョンの詳細:*ロールバックの前後で、RKE2およびコンポーネントのバージョンを必ず確認してください。

== RKE2クラスターのロールバック

[tabs]
=====
SQLite::
+
--

SQLiteデータベースを使用してRKE2クラスターをロールバックするには、`.db`ファイルを、データベースのバックアップ時に作成した`.db`ファイルのコピーと置き換えてください。

--

組み込みetcd::
+
--

組み込みetcd（デフォルト）の場合、RKE2クラスターのロールバックには、次の手順に従ってください：

. クラスターが実行中でKubernetes APIが利用可能な場合、すべてのノードをドレインしてワークロードを優雅に停止します:
+
[,bash]
----
 kubectl drain --ignore-daemonsets --delete-emptydir-data <NODE-ONE-NAME> <NODE-TWO-NAME> <NODE-THREE-NAME> ...
----

. 各ノードで、RKE2サービスおよびすべての実行中のポッドプロセスを停止してください：
+
[,bash]
----
 rke2-killall.sh
----

. 各ノードで、RKE2バイナリを前のバージョンにロールバックしてください。
 ** インターネットアクセスのあるクラスター:
  *** サーバーノード:
+
[,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Zrke2r1 sh -
----

  *** エージェントノード:
+
[,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Zrke2r1 INSTALL_RKE2_TYPE=agent sh -
----
 ** エアギャップ(された)クラスター:
  *** アーティファクトをダウンロードし、xref:install/airgap.adoc#_install_rke2[install script]をローカルで実行してください。
. 最初のサーバーノード、または`server:`xref:install/configuration.adoc[RKE2 config file]にエントリがないノードで、クラスターの復元を開始してください。詳細については、xref:datastore/backup_restore.adoc#_snapshot_restore_steps[Snapshot Restore Steps]を参照してください：
+
[,bash]
----
 rke2 server --cluster-reset --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>
----
+
[WARNING]
==== 
これはetcdデータストア内のすべてのデータを上書きします。復元する前にスナップショットの整合性を確認してください。大きなスナップショットは復元に時間がかかる場合があることに注意してください。
====

. 最初のサーバーノードでRKE2サービスを開始してください：
+
[,bash]
----
 systemctl start rke2-server
----

. 他のサーバーノードで、RKE2のデータベースディレクトリを削除してください：
+
[,bash]
----
 rm -rf /var/lib/rancher/rke2/server/db
----

. 他のサーバーノードでRKE2サービスを開始してください：
+
[,bash]
----
 systemctl start rke2-server
----

. すべてのエージェントノードでRKE2サービスを開始してください：
+
[,bash]
----
 systemctl start rke2-agent
----

. `systemctl status rke2-server`または`systemctl status rke2-agent`を使用して、RKE2サービスの状態を確認してください。

--

外部データベース::
+
--

外部データベース（例：PostgreSQL、MySQL）を使用してRKE2クラスターをロールバックするには、次の手順に従ってください：

. クラスターが実行中でKubernetes APIが利用可能な場合、すべてのノードをドレインしてワークロードを優雅に停止します:
+
[,bash]
----
 kubectl drain --ignore-daemonsets --delete-emptydir-data <NODE-ONE-NAME> <NODE-TWO-NAME> <NODE-THREE-NAME> ...
----
+
[NOTE]
==== 
このプロセスは、実行中のアプリケーションに影響を与える可能性があります。
====

. 各ノードで、RKE2サービスとすべての実行中のポッドプロセスを停止します：
+
[,bash]
----
 rke2-killall.sh
----

. RKE2のアップグレード前に取得したデータベーススナップショットを復元し、データベースの整合性を確認してください。例えば、PostgreSQLを使用している場合は、次のコマンドを実行してください：
+
[,bash]
----
 pg_restore -U <DB-USER> -d <DB-NAME> <BACKUP-FILE>
----

. 各ノードで、RKE2のバイナリを前のバージョンにロールバックします。
 ** インターネットアクセスのあるクラスター:
  *** サーバーノード:
+
[,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Zrke2r1 sh -
----

  *** エージェントノード:
+
[,bash]
----
curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=vX.Y.Zrke2r1 INSTALL_RKE2_TYPE=agent sh -
----
 ** エアギャップ(された)クラスター:
  *** アーティファクトをダウンロードし、xref:install/airgap.adoc#_install_rke2[install script]をローカルで実行してください。
. 各ノードでRKE2サービスを開始します：
+
[,bash]
----
 systemctl start rke2-server #or rke2-agent
----

. `systemctl status rke2-server`または`systemctl status rke2-agent`を使用して、RKE2サービスの状態を確認してください。

--

=====

== 検証

ロールバック後、次のことを確認してください：

* RKE2のバージョン：`rke2 --version`
* Kubernetesクラスタの健康状態：`kubectl get nodes`
* アプリケーションの機能。
* RKE2のログでエラーを確認してください。
