= Windows Air-Gap Install
:page-languages: [en, zh]
:revdate: 2025-08-06
:page-revdate: {revdate}

*Der Windows-Support erfordert die Verwendung von Calico oder Flannel als CNI für den RKE2-Cluster.*

Sie können RKE2 Windows-Agenten (Worker) Knoten in einer Air-Gapped-Umgebung mit zwei verschiedenen Methoden verwenden. Dazu muss zunächst das RKE2 xref:install/airgap.adoc[Air-Gap-Setup] abgeschlossen werden.

[IMPORTANT]
====
Sie können jede RKE2 Prime-Version verwenden, die auf der Prime Artifacts-URL für die in diesen Schritten genannten Assets aufgeführt ist. Um mehr über die Prime Artifacts-URL zu erfahren, siehe unsere https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime-only-Dokumentation]. Eine Authentifizierung ist erforderlich. Verwenden Sie Ihre https://scc.suse.com/home[SUSE Customer Center (SCC)]-Anmeldeinformationen, um sich anzumelden.
====

Laden Sie die Air Gap-Images TAR-Archive für Ihre RKE2-Version herunter oder verwenden Sie eine private Registry. Derzeit sind drei Tarball-Artefakte für Windows gemäß unseren validierten xref:install/requirements.adoc#_windows[Windows-Versionen] veröffentlicht.

* `rke2.windows-amd64.tar.gz`
* `rke2-windows-1809-amd64-images.tar.gz`
* `rke2-windows-ltsc2022-amd64-images.tar.gz`

Alle in den Schritten genannten Dateien können von der https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL] für Ihre gewünschte RKE2-Version bezogen werden.

== Bereiten Sie den Windows-Agent-Knoten vor

[NOTE]
====
Die Windows-Server-Container-Funktion muss aktiviert sein, damit der RKE2-Agent korrekt funktioniert.
====

. Öffnen Sie ein neues Powershell-Fenster mit Administratorrechten.
+
[,powershell]
----
powershell -Command "Start-Process PowerShell -Verb RunAs"
----

. Führen Sie im neuen Powershell-Fenster den folgenden Befehl aus.
+
[,powershell]
----
Enable-WindowsOptionalFeature -Online -FeatureName containers –All
----

. Starten Sie den Knoten neu, damit die `Containers` Funktion korrekt funktioniert.

== Windows-Tarball-Methode

. Laden Sie die Windows-Images-Tarballs und die Binärdatei von der https://scc.suse.com/rancher-docs/rancherprime/latest/en/reference-guide.html#prime-artifacts-url[Prime Artifacts URL] für die von Ihnen verwendete RKE2-Version herunter.
+
**Verwendung von tar.gz-Image-Tarballs**

** *Windows Server*
+
[,powershell]
----
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest <PRIME-Artifacts-URL>/rke2/<VERSION>/rke2.windows-amd64.tar.gz -OutFile /var/lib/rancher/rke2/agent/images/rke2.windows-amd64.tar.gz
----
+
** *Windows Server 2019 LTSC (amd64) (OS Build 17763.2061)*
+
[,powershell]
----
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest <PRIME-Artifacts-URL>/rke2/<VERSION>/rke2-windows-1809-amd64-images.tar.gz -OutFile c:/var/lib/rancher/rke2/agent/images/rke2-windows-1809-amd64-images.tar.gz
----
+
** *Windows Server 2022 LTSC (amd64) (OS Build 20348.169)*
+
[,powershell]
----
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest <PRIME-Artifacts-URL>/rke2/<VERSION>/rke2-windows-ltsc2022-amd64-images.tar.gz -OutFile c:/var/lib/rancher/rke2/agent/images/rke2-windows-ltsc2022-amd64-images.tar.gz
----
+
**Verwendung von tar.zst-Image-Tarballs**

Zstandard bietet im Vergleich zu pigz bessere Kompressionsverhältnisse und schnellere Dekompressionsgeschwindigkeiten.

** *Windows Server 2019 LTSC (amd64) (OS Build 17763.2061)*
+
[,powershell]
----
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest <PRIME-Artifacts-URL>/rke2/<VERSION>/rke2-windows-1809-amd64-images.tar.zst -OutFile /var/lib/rancher/rke2/agent/images/rke2-windows-1809-amd64-images.tar.zst
----
+
** *Windows Server 2022 LTSC (amd64) (OS Build 20348.169)*
+
[,powershell]
----
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest <PRIME-Artifacts-URL>/rke2/<VERSION>/rke2-windows-ltsc2022-amd64-images.tar.zst -OutFile c:/var/lib/rancher/rke2/agent/images/rke2-windows-ltsc2022-amd64-images.tar.zst
----
+
** Verwenden Sie `rke2-windows-<VERSION>-amd64.tar.gz` oder `rke2-windows-<VERSION>-amd64.tar.zst`. Zstandard bietet im Vergleich zu pigz bessere Kompressionsverhältnisse und schnellere Dekompressionsgeschwindigkeiten.
+
. Stellen Sie sicher, dass das `/var/lib/rancher/rke2/agent/images/` Verzeichnis auf dem Knoten vorhanden ist.
+
[,powershell]
----
 New-Item -Type Directory c:\usr\local\bin -Force
 New-Item -Type Directory c:\var\lib\rancher\rke2\bin -Force
----
. Kopieren Sie das komprimierte Archiv nach `/var/lib/rancher/rke2/agent/images/` auf dem Knoten und stellen Sie sicher, dass die Dateiendung beibehalten wird.
. <<Install Windows RKE2>>.

== Private Registry-Methode

Die Unterstützung für private Registries berücksichtigt alle Einstellungen aus der xref:install/containerd_registry_configuration.adoc[containerd-Registry-Konfiguration], einschließlich der Überschreibung des Endpunkts, des Transportprotokolls (HTTP/HTTPS), der Authentifizierung, der Zertifikatsüberprüfung und mehr.

. Fügen Sie alle erforderlichen Systembilder zu Ihrer privaten Registry hinzu. Eine Liste der Bilder kann aus der `.txt` Datei abgerufen werden, die jedem oben genannten Tarball entspricht. Alternativ können Sie die `docker load` TAR-Archive herunterladen, dann die geladenen Bilder taggen und pushen.
. <<Install Windows RKE2>> mit dem `system-default-registry` Parameter, oder verwenden Sie die xref:install/containerd_registry_configuration.adoc[containerd-Registry-Konfiguration], um Ihre Registry als Spiegel für docker.io zu verwenden.

== Install Windows RKE2

Diese Schritte sollten nur nach Abschluss einer der beiden Methoden <<Windows Tarball Method,Tarball-Methode>> oder <<Private Registry Method>> durchgeführt werden.

. Erhalten Sie die Windows RKE2-Binärdatei `rke2-windows-amd64.exe`. Stellen Sie sicher, dass die Binärdatei den Namen `rke2.exe` trägt und sich in `c:/usr/local/bin` befindet.
+
[,powershell]
----
Invoke-WebRequest <PRIME-Artifacts-URL>/rke2/<VERSION>/rke2-windows-amd64.exe -OutFile c:/usr/local/bin/rke2.exe
----

. Konfigurieren Sie den rke2-agent für Windows.
+
[,powershell]
----
New-Item -Type Directory c:/etc/rancher/rke2 -Force
Set-Content -Path c:/etc/rancher/rke2/config.yaml -Value @"
server: https://<server>:9345
token: <token from server node>
"@
----
+
Um mehr über die Datei config.yaml zu erfahren, siehe die xref:install/configuration.adoc#_configuration_file[Dokumentation zu Installationsoptionen.]

. Konfigurieren Sie Ihren PATH.
+
[,powershell]
----
$env:PATH+=";c:\var\lib\rancher\rke2\bin;c:\usr\local\bin"

"Path",
[Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";c:\var\lib\rancher\rke2\bin;c:\usr\local\bin",
[EnvironmentVariableTarget]::Machine)
----

. Starten Sie den RKE2 Windows-Dienst, indem Sie die Binärdatei mit den gewünschten Parametern ausführen. Bitte beachten Sie die xref:reference/windows_agent_config.adoc[Referenz zur Windows-Agent-Konfiguration] für zusätzliche Parameter.
+
[,powershell]
----
c:\usr\local\bin\rke2.exe agent service --add
Start-Service rke2
----
+
* Wenn Sie die Rancher Prime-Registry verwenden, setzen Sie die folgenden Werte in `config.yaml`:
.. Setzen Sie `system-default-registry: registry.rancher.com`.
.. Wenn Sie nicht das Standard-CNI, Canal, verwenden, setzen Sie `cni: <CNI>`.
+
[,yaml]
----
system-default-registry: registry.rancher.com
cni: <CNI>
----
* Wenn Sie die Private Registry-Methode verwenden, setzen Sie die folgenden Werte in `config.yaml`:
+
[,yaml]
----
system-default-registry: "registry.example.com:5000"
----
+
[NOTE] 
====
Der `system-default-registry`-Parameter muss ausschließlich gültige RFC 3986-URI-Autoritäten angeben, d. h. einen Host und einen optionalen Port.
====
+
Wenn Sie lieber ausschließlich Parameter der Kommandozeilenschnittstelle verwenden möchten, führen Sie die Binärdatei mit den gewünschten Parametern aus.
+
[,powershell]
----
c:/usr/local/bin/rke2.exe agent --token <> --server <>
----
