= 简介
:page-languages: [en, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}

image::logo-horizontal-rke2.svg[RKE2 Logo, 346,111]

{product-name} 是 Rancher 的企业级下一代 Kubernetes 发行版。它也被称为 RKE 政府版。

它是一款完全符合认证标准的 https://landscape.cncf.io/?group=projects-and-products&view-mode=card&item=platform--certified-kubernetes-distribution--rke-government#app-definition-and-development--application-definition-image-build[Kubernetes 发行版]，专注于美国的安全和合规性。安全和合规要求。

为了实现这些目标，{product-name} 采取了以下措施：

* 提供 xref:security/hardening_guide.adoc[默认设置和配置选项]，使群集能够在最少的运维干预下通过 CIS Kubernetes Benchmark xref:security/cis_self_assessment19.adoc[v1.9] 或 xref:security/cis_self_assessment110.adoc[v1.10] 认证。
* 支持 xref:security/fips3_support.adoc[FIPS 140-3 合规性]。
* 定期使用 https://github.com/aquasecurity/trivy[trivy] 在我们的构建管道中扫描组件以查找 CVE。

== 这与 RKE 或 {k3s-product-name} 有何不同？

{product-name} 结合了 RKE 1.x 版本（以下简称 RKE1）和 {k3s-product-name} 的优点。

从 {k3s-product-name} 中，它继承了可用性、操作简便性和部署模型。

从 RKE1 中，它继承了与上游 Kubernetes 的紧密对齐。在某些地方，{k3s-product-name} 为了优化边缘部署而与上游 Kubernetes 有所不同，但 RKE1 和 RKE2 可以与上游保持紧密对齐。

重要的是，{product-name} 不像 RKE1 那样依赖 Docker。RKE1 利用 Docker 部署和管理控制平面组件以及 Kubernetes 的容器运行时。RKE2 将控制平面组件作为静态 Pod 启动，由 kubelet 管理。嵌入的容器运行时是 containerd。

== 为什么有两个名称？

它被称为 {product-name}，因为它是 Rancher Kubernetes Engine 在数据中心用例中的下一次迭代。该发行版可以独立运行或集成到Rancher中。在 Rancher v2.6+ 中支持新 {product-name} 集群的自动化预配。

它也被称为 RKE 政府版，因为它旨在针对安全要求更高的领域。

== 安全性

Rancher Labs支持负责任的披露，并努力在合理的时间内解决安全问题。要报告安全漏洞，请发送电子邮件至 link:mailto:security@rancher.com[security@rancher.com]。
