= Embedded datastore
:revdate: 2025-08-08
:page-revdate: {revdate}

Using an embedded datastore means leveraging a database that runs within the Kubernetes cluster, typically as a containerized service, e.g. etcd. This option simplifies deployment and could improve performance and security. The alternative is xref:datastore/external.adoc[external databases].

== Datastore options

[WARNING]
.Experimental
====
RKE2 officially supports Embedded etcd, embedded SQLite is considered experimental.
====

* *Embedded https://etcd.io/[etcd]*: Embedded etcd is the default datastore, and will be used if no other datastore configuration is present.
* *Embedded https://www.sqlite.org/index.html[SQLite]*: SQLite cannot be used on clusters with multiple servers. It uses project https://github.com/k3s-io/kine[kine].

== Embedded etcd

Embedded https://etcd.io/[etcd]is the default datastore, and will be used if no other datastore configuration is present.  It is the only embedded option that allows to deploy RKE2 in xref:install/ha.adoc[HA mode]. Unless explicitly unset, one etcd pod will be deployed per RKE2 server and all the etcd instances will maintain a quorum. RKE2 includes tools to easily create snapshots when using this datastore as explained in the xref:datastore/backup_restore.adoc[Backup and Restore] instructions.

== Embedded SQLite

This embedded option is not recommended for production but can be useful if you need to run a simple, short-lived cluster, for example in a CI/CD environment. HA mode is not supported when deploying with https://www.sqlite.org/index.html[SQLite].

=== Single Server with SQLite

. Set `disable-etcd` without the `server` parameter in the config file.
+
[,yaml]
----
disable-etcd: true
----

. Install RKE2.
+
[,bash]
----
curl -sfL https://get.rke2.io | sh -
----

. Enable rke2-server service.
+
[,sh]
----
systemctl enable rke2-server.service
----

. Start the rke2-server service.
+
[,sh]
----
systemctl start rke2-server.service
----

You can follow the server starting by `kubectl get nodes` to see the server get the `Ready` status. See xref:cluster_access.adoc[Cluster access] for more info about how to access RKE2.