= Windows et BGP
:page-languages: [en, zh]
:revdate: 2025-10-29
:page-revdate: {revdate}

== Activation de BGP sur Calico avec Windows

Pour activer le mode BGP pour le routage du trafic avec RKE2 en utilisant à la fois des nœuds Linux et Windows, le CNI Calico doit être sélectionné dans la configuration du serveur.

[,yaml]
----
# /etc/rancher/rke2/config.yaml
cni: calico
----

Calico doit ensuite être configuré avec BGP activé et encapsulation définie sur `None`.

[,yaml]
----
# /var/lib/rancher/rke2/server/manifests/rke2-calico-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
      backend: "None"
----

== Démarrage du nœud Windows

Configurez RKE2 sur le nœud Windows comme décrit xref:install/quickstart.adoc#_windows_agent_worker_node_installation[ici].

Avant de démarrer le service RKE2, `RemoteAccess` doit être activé.

[,powershell]
----
Install-WindowsFeature RemoteAccess
Install-WindowsFeature RSAT-RemoteAccess-PowerShell
Install-WindowsFeature Routing
----

Cela nécessite un redémarrage pour fonctionner correctement.

Ensuite, configurez le service `RemoteAccess` :

[,powershell]
----
Install-RemoteAccess -VpnType RoutingOnly
----

Pour vérifier si le service `RemoteAccess` a démarré correctement, utilisez la commande suivante :

[,powershell]
----
Start-Service RemoteAccess
----

Après cela, vous pouvez démarrer le service RKE2.
